# 应用端口
server:
  port: 8090

# 应用名称
spring:
  application:
    name: payment-study
  # swagger2 兼容性配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_study?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 12345678

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/example/paymentstudy/mapper/xml/*.xml